{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "oms.fullname" . }}
  labels:
    {{- include "oms.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "oms.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: IfHealthyBudget
{{- end }}
