apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: oms
  namespace: oms
  labels:
    app: oms
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: oms
  unhealthyPodEvictionPolicy: IfHealthyBudget
